### ISSUE TITLE
Update lexer to return string name of variable

### ISSUE THREAD

**Issue by TrikkStar** [TrikkStar/Alpaca#9]
the lexer needs to be given a regular expression which will return the string value between `let` and `=`.
eg. return `expr` from `let expr = ...`

@Skiadas How would you make this regular;ar expression?

**Comment by skiadas** [comment]
What does the lexer have to do with this? The lexer reads the keyword "let", then an identifier, then the equal sign, sends all 3 tokens to the parser.

Didn't we solve this problem in assignment 8?
